/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as UitschrijvenRouteImport } from './routes/uitschrijven'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AnnuleerRouteImport } from './routes/annuleer'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WinkelIndexRouteImport } from './routes/winkel/index'
import { Route as BoekenIndexRouteImport } from './routes/boeken/index'
import { Route as WinkelSuccesRouteImport } from './routes/winkel/succes'
import { Route as WinkelMisluktRouteImport } from './routes/winkel/mislukt'
import { Route as WinkelCheckoutRouteImport } from './routes/winkel/checkout'
import { Route as WinkelIdRouteImport } from './routes/winkel/$id'
import { Route as ReviewBookingIdRouteImport } from './routes/review.$bookingId'
import { Route as BoekenVerlopenRouteImport } from './routes/boeken/verlopen'
import { Route as BoekenSuccesRouteImport } from './routes/boeken/succes'

const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const UitschrijvenRoute = UitschrijvenRouteImport.update({
  id: '/uitschrijven',
  path: '/uitschrijven',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuleerRoute = AnnuleerRouteImport.update({
  id: '/annuleer',
  path: '/annuleer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelIndexRoute = WinkelIndexRouteImport.update({
  id: '/winkel/',
  path: '/winkel/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekenIndexRoute = BoekenIndexRouteImport.update({
  id: '/boeken/',
  path: '/boeken/',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelSuccesRoute = WinkelSuccesRouteImport.update({
  id: '/winkel/succes',
  path: '/winkel/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelMisluktRoute = WinkelMisluktRouteImport.update({
  id: '/winkel/mislukt',
  path: '/winkel/mislukt',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelCheckoutRoute = WinkelCheckoutRouteImport.update({
  id: '/winkel/checkout',
  path: '/winkel/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelIdRoute = WinkelIdRouteImport.update({
  id: '/winkel/$id',
  path: '/winkel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewBookingIdRoute = ReviewBookingIdRouteImport.update({
  id: '/review/$bookingId',
  path: '/review/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekenVerlopenRoute = BoekenVerlopenRouteImport.update({
  id: '/boeken/verlopen',
  path: '/boeken/verlopen',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekenSuccesRoute = BoekenSuccesRouteImport.update({
  id: '/boeken/succes',
  path: '/boeken/succes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/annuleer': typeof AnnuleerRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uitschrijven': typeof UitschrijvenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/boeken/succes': typeof BoekenSuccesRoute
  '/boeken/verlopen': typeof BoekenVerlopenRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/winkel/$id': typeof WinkelIdRoute
  '/winkel/checkout': typeof WinkelCheckoutRoute
  '/winkel/mislukt': typeof WinkelMisluktRoute
  '/winkel/succes': typeof WinkelSuccesRoute
  '/boeken/': typeof BoekenIndexRoute
  '/winkel/': typeof WinkelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/annuleer': typeof AnnuleerRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uitschrijven': typeof UitschrijvenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/boeken/succes': typeof BoekenSuccesRoute
  '/boeken/verlopen': typeof BoekenVerlopenRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/winkel/$id': typeof WinkelIdRoute
  '/winkel/checkout': typeof WinkelCheckoutRoute
  '/winkel/mislukt': typeof WinkelMisluktRoute
  '/winkel/succes': typeof WinkelSuccesRoute
  '/boeken': typeof BoekenIndexRoute
  '/winkel': typeof WinkelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/annuleer': typeof AnnuleerRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uitschrijven': typeof UitschrijvenRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/boeken/succes': typeof BoekenSuccesRoute
  '/boeken/verlopen': typeof BoekenVerlopenRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/winkel/$id': typeof WinkelIdRoute
  '/winkel/checkout': typeof WinkelCheckoutRoute
  '/winkel/mislukt': typeof WinkelMisluktRoute
  '/winkel/succes': typeof WinkelSuccesRoute
  '/boeken/': typeof BoekenIndexRoute
  '/winkel/': typeof WinkelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/annuleer'
    | '/cookies'
    | '/privacy'
    | '/sitemap.xml'
    | '/uitschrijven'
    | '/voorwaarden'
    | '/boeken/succes'
    | '/boeken/verlopen'
    | '/review/$bookingId'
    | '/winkel/$id'
    | '/winkel/checkout'
    | '/winkel/mislukt'
    | '/winkel/succes'
    | '/boeken/'
    | '/winkel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/annuleer'
    | '/cookies'
    | '/privacy'
    | '/sitemap.xml'
    | '/uitschrijven'
    | '/voorwaarden'
    | '/boeken/succes'
    | '/boeken/verlopen'
    | '/review/$bookingId'
    | '/winkel/$id'
    | '/winkel/checkout'
    | '/winkel/mislukt'
    | '/winkel/succes'
    | '/boeken'
    | '/winkel'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/annuleer'
    | '/cookies'
    | '/privacy'
    | '/sitemap.xml'
    | '/uitschrijven'
    | '/voorwaarden'
    | '/boeken/succes'
    | '/boeken/verlopen'
    | '/review/$bookingId'
    | '/winkel/$id'
    | '/winkel/checkout'
    | '/winkel/mislukt'
    | '/winkel/succes'
    | '/boeken/'
    | '/winkel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AnnuleerRoute: typeof AnnuleerRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UitschrijvenRoute: typeof UitschrijvenRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  BoekenSuccesRoute: typeof BoekenSuccesRoute
  BoekenVerlopenRoute: typeof BoekenVerlopenRoute
  ReviewBookingIdRoute: typeof ReviewBookingIdRoute
  WinkelIdRoute: typeof WinkelIdRoute
  WinkelCheckoutRoute: typeof WinkelCheckoutRoute
  WinkelMisluktRoute: typeof WinkelMisluktRoute
  WinkelSuccesRoute: typeof WinkelSuccesRoute
  BoekenIndexRoute: typeof BoekenIndexRoute
  WinkelIndexRoute: typeof WinkelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uitschrijven': {
      id: '/uitschrijven'
      path: '/uitschrijven'
      fullPath: '/uitschrijven'
      preLoaderRoute: typeof UitschrijvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuleer': {
      id: '/annuleer'
      path: '/annuleer'
      fullPath: '/annuleer'
      preLoaderRoute: typeof AnnuleerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkel/': {
      id: '/winkel/'
      path: '/winkel'
      fullPath: '/winkel/'
      preLoaderRoute: typeof WinkelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boeken/': {
      id: '/boeken/'
      path: '/boeken'
      fullPath: '/boeken/'
      preLoaderRoute: typeof BoekenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkel/succes': {
      id: '/winkel/succes'
      path: '/winkel/succes'
      fullPath: '/winkel/succes'
      preLoaderRoute: typeof WinkelSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkel/mislukt': {
      id: '/winkel/mislukt'
      path: '/winkel/mislukt'
      fullPath: '/winkel/mislukt'
      preLoaderRoute: typeof WinkelMisluktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkel/checkout': {
      id: '/winkel/checkout'
      path: '/winkel/checkout'
      fullPath: '/winkel/checkout'
      preLoaderRoute: typeof WinkelCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkel/$id': {
      id: '/winkel/$id'
      path: '/winkel/$id'
      fullPath: '/winkel/$id'
      preLoaderRoute: typeof WinkelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$bookingId': {
      id: '/review/$bookingId'
      path: '/review/$bookingId'
      fullPath: '/review/$bookingId'
      preLoaderRoute: typeof ReviewBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boeken/verlopen': {
      id: '/boeken/verlopen'
      path: '/boeken/verlopen'
      fullPath: '/boeken/verlopen'
      preLoaderRoute: typeof BoekenVerlopenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boeken/succes': {
      id: '/boeken/succes'
      path: '/boeken/succes'
      fullPath: '/boeken/succes'
      preLoaderRoute: typeof BoekenSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AnnuleerRoute: AnnuleerRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UitschrijvenRoute: UitschrijvenRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  BoekenSuccesRoute: BoekenSuccesRoute,
  BoekenVerlopenRoute: BoekenVerlopenRoute,
  ReviewBookingIdRoute: ReviewBookingIdRoute,
  WinkelIdRoute: WinkelIdRoute,
  WinkelCheckoutRoute: WinkelCheckoutRoute,
  WinkelMisluktRoute: WinkelMisluktRoute,
  WinkelSuccesRoute: WinkelSuccesRoute,
  BoekenIndexRoute: BoekenIndexRoute,
  WinkelIndexRoute: WinkelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
